from enum import Enum

class AronState(Enum):
    IDLE = "IDLE"
    INITIALIZING = "INITIALIZING"
    PLANNING = "PLANNING"
    CODING = "CODING"
    VISION_ANALYSIS = "VISION_ANALYSIS"
    VALIDATING = "VALIDATING"
    HEALING = "HEALING"
    ROLLBACK = "ROLLBACK"
    COMMITTING = "COMMITTING"
    ERROR = "ERROR"
